[theme]
primaryColor = "#0099d4"
backgroundColor = "#ffffff"
secondaryBackgroundColor = "#f0f2f6"
textColor = "#262730"
font = "sans serif"

[client]
showErrorDetails = false
showWarningOnDirectExecution = false

[logger]
level = "info"

[server]
headless = true
port = 8501
runOnSave = true
